apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-prometheus-client
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubearmor-prometheus-client
  template:
    metadata:
      labels:
        app: kubearmor-prometheus-client
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
    spec:
      containers:
      - name: kubearmor-prometheus-client
        image: localhost:5000/kubearmor-prometheus-client:v63
        env:
        - name: KUBEARMOR_SERVICE
          value: kubearmor.kube-system.svc:32767
        ports:
        - containerPort: 9100
