{
 "title": "Kubearmor Dashboard",
 "time": { "from": "2021-07-01T06:31:12.300Z", "to": "2021-07-01T06:31:12.304Z" },
 "panels": [
  {
   "title": "Number of logs in given Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_relay_logs_total_in_Namespace) by (NamespaceName)"
    }
   ]
  },
  {
   "title": "Number of logs on given Container ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_relay_logs_total_in_Container) by (ContainerName)"
    }
   ]
  },
  {
   "title": "Number of logs with given Action",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_relay_logs_with_action_total) by (Action)"
    }
   ]
  },
  {
   "title": "Number of logs on given Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_relay_logs_total_on_Pod) by (PodName)"
    }
   ]
  },
  {
   "title": "Number of logs with given Severity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_relay_logs_severity_total) by (Severity)"
    }
   ]
  },
  {
   "title": "Number of logs with given Policy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_relay_policy_logs_total) by (PolicyName)"
    }
   ]
  },
  {
   "title": "Number of logs with given Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_relay_logs_with_operation_total) by (Operation)"
    }
   ]
  },
  {
   "title": "Number of logs with given Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_relay_logs_with_type_total) by (Type)"
    }
   ]
  }
 ]
}